CREATE TABLE password_reset_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    token_hash  VARCHAR(64)                             NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used_at     TIMESTAMP WITHOUT TIME ZONE,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id),
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_password_reset_token_hash ON password_reset_tokens (token_hash);
