CREATE TYPE billing_cadence AS ENUM ('WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY');
CREATE TYPE product_status  AS ENUM ('ACTIVE', 'INACTIVE', 'DELETED');

CREATE TABLE products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id       BIGINT                                  NOT NULL,
    name            VARCHAR(200)                            NOT NULL,
    description     TEXT,
    price           NUMERIC(19, 4)                          NOT NULL,
    currency        VARCHAR(3)                              NOT NULL DEFAULT 'USD',
    billing_cadence billing_cadence                         NOT NULL,
    status          product_status                          NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,
    deleted_by      BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT fk_products_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE products
    ADD CONSTRAINT fk_products_on_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id);

CREATE INDEX idx_products_tenant_status ON products (tenant_id, status);
