CREATE TYPE customer_status AS ENUM ('ACTIVE', 'DELETED');

CREATE TABLE customers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id    BIGINT                                  NOT NULL,
    name         VARCHAR(200)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    phone        VARCHAR(50),
    address      TEXT,
    notes        TEXT,
    status       customer_status                         NOT NULL DEFAULT 'ACTIVE',
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_by   BIGINT,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

ALTER TABLE customers
    ADD CONSTRAINT uc_customers_tenant_email UNIQUE (tenant_id, email);

ALTER TABLE customers
    ADD CONSTRAINT fk_customers_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id);

ALTER TABLE customers
    ADD CONSTRAINT fk_customers_on_deleted_by FOREIGN KEY (deleted_by) REFERENCES users (id);

CREATE INDEX idx_customers_tenant_status ON customers (tenant_id, status);
