ALTER TABLE customer_products
    ADD COLUMN IF NOT EXISTS price    NUMERIC(19, 4)       NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS currency CHARACTER VARYING(3) NOT NULL DEFAULT 'USD';

ALTER TABLE customer_products
    ALTER COLUMN price    DROP DEFAULT,
    ALTER COLUMN currency DROP DEFAULT;
