package np.com.abhishekojha.coremonolith.common.enums;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public enum AuditAction {

    USER_LOGIN("USER.LOGIN"),
    USER_LOGOUT("USER.LOGOUT"),
    USER_LOGIN_FAILED("USER.LOGIN_FAILED"),
    USER_CREATED("USER.CREATED"),
    USER_ROLE_CHANGED("USER.ROLE_CHANGED"),
    USER_DISABLED("USER.DISABLED"),
    USER_DELETED("USER.DELETED"),

    TENANT_CREATED("TENANT.CREATED"),
    TENANT_UPDATED("TENANT.UPDATED"),
    TENANT_SUSPENDED("TENANT.SUSPENDED"),
    TENANT_REACTIVATED("TENANT.REACTIVATED"),
    TENANT_ARCHIVED("TENANT.ARCHIVED"),

    CUSTOMER_CREATED("CUSTOMER.CREATED"),
    CUSTOMER_UPDATED("CUSTOMER.UPDATED"),
    CUSTOMER_DELETED("CUSTOMER.DELETED"),

    PRODUCT_CREATED("PRODUCT.CREATED"),
    PRODUCT_UPDATED("PRODUCT.UPDATED"),
    PRODUCT_DELETED("PRODUCT.DELETED"),
    PRODUCT_ACTIVATED("PRODUCT.ACTIVATED"),
    PRODUCT_DEACTIVATED("PRODUCT.DEACTIVATED"),

    SUBSCRIPTION_CREATED("SUBSCRIPTION.CREATED"),
    SUBSCRIPTION_UPDATED("SUBSCRIPTION.UPDATED"),
    SUBSCRIPTION_ACTIVATED("SUBSCRIPTION.ACTIVATED"),
    SUBSCRIPTION_PAUSED("SUBSCRIPTION.PAUSED"),
    SUBSCRIPTION_CANCELLED("SUBSCRIPTION.CANCELLED"),
    SUBSCRIPTION_AUTO_CANCELLED("SUBSCRIPTION.AUTO_CANCELLED"),
    SUBSCRIPTION_DELETED("SUBSCRIPTION.DELETED"),

    INVITATION_CREATED("INVITATION.CREATED"),
    INVITATION_REVOKED("INVITATION.REVOKED"),
    INVITATION_ACCEPTED("INVITATION.ACCEPTED"),

    PLATFORM_PLAN_CREATED("PLATFORM_PLAN.CREATED"),
    PLATFORM_PLAN_UPDATED("PLATFORM_PLAN.UPDATED"),
    PLATFORM_PLAN_ARCHIVED("PLATFORM_PLAN.ARCHIVED"),

    TENANT_PLAN_ASSIGNED("TENANT_PLAN.ASSIGNED"),

    PASSWORD_RESET_REQUESTED("PASSWORD_RESET.REQUESTED"),
    PASSWORD_RESET_COMPLETED("PASSWORD_RESET.COMPLETED");

    private final String value;

    AuditAction(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    private static final Logger log = LoggerFactory.getLogger(AuditAction.class);

    public static AuditAction fromValue(String value) {
        for (AuditAction a : values()) {
            if (a.value.equals(value)) return a;
        }
        log.warn("Unknown AuditAction value '{}' in DB — falling back to USER_LOGIN", value);
        return USER_LOGIN;
    }
}
